language: python
matrix:
    include:
      # Python version is just for the look on travis.
        - python: 2.7
          env: TOX_ENV=py27-dj18
        - python: 2.7
          env: TOX_ENV=py27-dj110
        - python: 2.7
          env: TOX_ENV=py27-dj111

        - python: 3.4
          env: TOX_ENV=py34-dj18
        - python: 3.4
          env: TOX_ENV=py34-dj110
        - python: 3.4
          env: TOX_ENV=py34-dj111

        - python: 3.5
          env: TOX_ENV=py35-dj18
        - python: 3.5
          env: TOX_ENV=py35-dj110
        - python: 3.5
          env: TOX_ENV=py35-dj111

        - python: 3.6
          env: TOX_ENV=py36-dj111

before_install:
  - sudo apt-get -q -y update

  # The following three lines is a fix for travis CI, since it wouldn't be
  # able to install the dependencies correctly.
  # See: https://github.com/travis-ci/travis-ci/issues/2683
  - sudo apt-get remove -q -y binutils gdal-bin libproj-dev libgeos-c1
  - sudo add-apt-repository -y ppa:ubuntugis/ubuntugis-unstable

  # Required to install Pillow
  - sudo apt-get -q -y install build-essential
  # GIS requirements.
  - sudo apt-get -q -y install binutils gdal-bin libproj-dev libgeos-c1

install:
  - pip install tox
script:
  - tox -e $TOX_ENV

notifications:
  irc:
    channels:
      - "irc.freenode.org#django-floppyforms"
    on_success: change
    on_failure: always
deploy:
  provider: pypi
  user: gremu
  password:
    secure: HAgxb7ebUfIQSfcxtjKoXO3FCBiujCo4GU2lYO8IUPeSdurPG6e+uABzwg88d7Zt1Zuay2eleAJzqhvwU2bCOKr68wjkNw3yWRslvLAMK3vj2LPPoWYsgmLJ1YiOvPloCdD2sIVSmpLEiN5HLUteh5j6D2BUbw67a9S2TXx1J8c=
  on:
    tags: true
    repo: gregmuellegger/django-floppyforms
    condition: "$TOXENV = py35-18"
